version: 1
formatters:
  simple:
    format: '[%(asctime)s](%(name)s) %(filename)10s: %(lineno)-4s- PID: %(process)-4d - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  develop:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]